# Generated by Django 4.0.1 on 2022-01-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contractors',
            new_name='Contractor',
        ),
    ]
