# Generated by Django 4.0.1 on 2022-01-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_contractors_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
