# Generated by Django 4.0.1 on 2022-01-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_service_search_product_and_more'),
        ('users', '0003_alter_contractor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='product',
            field=models.ManyToManyField(to='app.Product'),
        ),
    ]
