# Generated by Django 4.0.1 on 2022-08-20 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_alter_choice_label_alter_choice_value_and_more"),
        ("users", "0004_contractor_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="about",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="contractor",
            name="address",
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contractor",
            name="company_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="contractor",
            name="company_person",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="contractor",
            name="email",
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contractor",
            name="experties",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.choice"
            ),
        ),
        migrations.AddField(
            model_name="contractor",
            name="field",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contractor",
            name="phone_number",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
