# Generated by Django 4.0.1 on 2022-08-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_alter_choice_label_alter_choice_value_and_more"),
        ("users", "0005_contractor_about_contractor_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="internal_notes",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="contractor",
            name="experties",
        ),
        migrations.AddField(
            model_name="contractor",
            name="experties",
            field=models.ManyToManyField(to="app.Choice"),
        ),
    ]
