# Generated by Django 4.0.1 on 2022-08-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_contractor_internal_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contractor",
            name="internal_notes",
        ),
        migrations.RemoveField(
            model_name="contractor",
            name="name",
        ),
        migrations.AddField(
            model_name="contractor",
            name="website",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="address",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="field",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="phone_number",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contractor",
            name="zip_code",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
