# Generated by Django 4.0.1 on 2022-08-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_contractor_internal_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="internal_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
