# Generated by Django 4.0.1 on 2022-08-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_contractor_internal_notes_contractor_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="service_area",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
