# Generated by Django 4.0.1 on 2022-09-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_contractor_service_area"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contractor",
        ),
    ]
