# Generated by Django 4.0.1 on 2022-01-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_choice_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='product',
        ),
        migrations.AddField(
            model_name='question',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product'),
        ),
    ]
