# Generated by Django 4.0.1 on 2022-01-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_contractors_contractor'),
        ('app', '0004_remove_product_pub_date_remove_question_pub_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contractors',
            field=models.ManyToManyField(to='users.Contractor'),
        ),
    ]
