# Generated by Django 4.0.1 on 2022-01-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_contractors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_text',
            new_name='name',
        ),
    ]
