# Generated by Django 4.0.1 on 2022-01-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_question_choices_choice_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='service',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='contractors',
        ),
        migrations.RemoveField(
            model_name='search',
            name='client',
        ),
        migrations.AddField(
            model_name='search',
            name='email',
            field=models.EmailField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='first_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='last_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='number',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
