# Generated by Django 4.0.1 on 2022-01-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_service_search_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='Searche',
        ),
    ]
