# Generated by Django 4.0.1 on 2022-01-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_choice_question_alter_question_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searche',
            name='project_location',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
