# Generated by Django 4.0.1 on 2022-02-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_searche_project_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['product']},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ManyToManyField(null=True, to='app.Question'),
        ),
    ]
