# Generated by Django 4.0.1 on 2022-02-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_variant_product_price_product_price_with_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='variant',
            name='price_with_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_stock_online', models.BooleanField(default=True)),
                ('in_stock_physical', models.BooleanField(default=True)),
                ('brief_description', models.TextField()),
                ('original_description', models.TextField()),
                ('technical_description', models.TextField()),
                ('delivery_time', models.DateField()),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('return_information', models.TextField()),
                ('contact_infomation', models.TextField()),
                ('help_information', models.TextField()),
                ('product_warranty', models.TextField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product')),
            ],
        ),
    ]
