# Generated by Django 4.0.1 on 2022-07-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_question_is_active_question_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choice',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
