# Generated by Django 4.0.1 on 2022-07-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_choice_is_active_choice_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='service_label',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question_label',
        ),
        migrations.AddField(
            model_name='choice',
            name='value',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='service',
            field=models.SlugField(default='Test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='is_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.SlugField(default='Test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('RadioQuestion', 'Radio Question'), ('CheckboxQuestion', 'Checkbox Question'), ('DropdownQuestion', 'Dropdown Question')], default='RadioQuestion', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QuestionChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.ManyToManyField(to='app.Choice')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.question')),
            ],
        ),
    ]
