# Generated by Django 4.0.1 on 2022-07-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_choice_text_choice_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='question_slug',
        ),
    ]
