# Generated by Django 4.0.1 on 2022-07-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_name_question_question_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='service',
            new_name='service_slug',
        ),
    ]
