# Generated by Django 4.0.1 on 2022-07-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_choice_question_question_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='choices',
        ),
    ]
