# Generated by Django 4.0.1 on 2022-07-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_service_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='question',
            field=models.ManyToManyField(to='app.Question'),
        ),
    ]
