# Generated by Django 4.0.1 on 2022-07-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_question_product_product_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='question',
            field=models.ManyToManyField(null=True, to='app.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(null=True, to='app.Choice'),
        ),
    ]
