# Generated by Django 4.0.1 on 2022-07-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_product_question_alter_question_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(to='app.Choice'),
        ),
    ]
