# Generated by Django 4.0.1 on 2022-07-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_product_question_question_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, to='app.Choice'),
        ),
    ]
