# Generated by Django 4.0.1 on 2022-07-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_question_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searche',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='searche',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='searche',
            name='email',
        ),
        migrations.RemoveField(
            model_name='searche',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='searche',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='searche',
            name='number',
        ),
        migrations.RemoveField(
            model_name='searche',
            name='project_location',
        ),
        migrations.RemoveField(
            model_name='searche',
            name='question',
        ),
        migrations.AddField(
            model_name='searche',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='searche',
            name='answer',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='searche',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='searche',
            name='location_langitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='searche',
            name='location_longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='searche',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
