# Generated by Django 4.0.1 on 2022-07-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_rename_product_searche_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searche',
            name='zip_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
