# Generated by Django 4.0.1 on 2022-08-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_searche_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='label',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
