# Generated by Django 4.0.1 on 2022-08-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_choice_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='service_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
