# Generated by Django 4.0.1 on 2022-08-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_product_service_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='label',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='choice',
            name='value',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='service_label',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='service_slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
