# Generated by Django 4.0.1 on 2022-09-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_contractor_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="searche",
            name="choice",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="app.choice"
            ),
        ),
        migrations.AddField(
            model_name="searche",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.question",
            ),
        ),
    ]
