# Generated by Django 4.0.1 on 2022-09-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_searche_choice_searche_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="searche",
            name="choice",
        ),
        migrations.RemoveField(
            model_name="searche",
            name="question",
        ),
    ]
