# Generated by Django 4.0.1 on 2022-09-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_remove_searche_choice_remove_searche_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="searche",
            old_name="product_id",
            new_name="product",
        ),
    ]
