# Generated by Django 4.0.1 on 2022-09-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_rename_product_id_searche_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searche",
            name="zip_code",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
