# Generated by Django 4.0.1 on 2022-09-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_alter_searche_zip_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="location_langitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contractor",
            name="location_longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
