# Generated by Django 4.0.1 on 2022-09-10 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_remove_result_searche_searche_result"),
    ]

    operations = [
        migrations.RenameField(
            model_name="searche",
            old_name="zip_code",
            new_name="project_location",
        ),
    ]
