# Generated by Django 4.0.1 on 2022-09-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_rename_zip_code_searche_project_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searche",
            name="location_langitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="searche",
            name="location_longitude",
            field=models.FloatField(),
        ),
    ]
